

export const supaUrl = 'https://kkrpmrjxgjrrjcatizoi.supabase.co'

export const anoKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcnBtcmp4Z2pycmpjYXRpem9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDg0NTMsImV4cCI6MjA1MjAyNDQ1M30.z3alVJqnGI1te9JuXXIVh1SONmGU8q4cx9IAEjukzyA'